name: "rewriteReadme"
on:
  issues:
    types: [closed]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
     
      - name: Generate Post
        env:
          POST_TITLE: ${{ github.event.issue.title }}
          POST_BODY: ${{ github.event.comment.body }}
          # POST_labels: ${{ github.event.comment.body }}
        run: |
          sudo chown $USER:$GROUPS $GITHUB_WORKSPACE
          preprocess_bin="$GITHUB_WORKSPACE/frontmatterify"
          save_to="content/posts"
          # mkdir "$save_to"
          cd "$save_to"
          sudo $GITHUB_WORKSPACE/frontmatterify > index.md << EOF
          $POST_BODY
          EOF
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "publish: ${{ github.event.issue.title}}"
          body: |
            Automagically sprouted for publishing.
            Merging will publish to: https://xxxx.xx/posts/${{ github.event.issue.title }}
            Closes #${{ github.event.issue.number }}
          reviewers: "${{ github.repository_owner }}"
          commit-message: "post: ${{ github.event.issue.title }}"
          
      - name: 1Auto Issue List in README
        uses: zhang0ZGC/issue-list-readme@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- 1issueTable -->"
          state: "closed"
          labels: "生信技能树,fetched"
          creator: "ixxmu"
          per_page: 10
      - name: 2Auto Issue List in README
        uses: zhang0ZGC/issue-list-readme@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- 2issueTable -->"
          state: "closed"
          labels: "单细胞天地,fetched"
          creator: "ixxmu"
          per_page: 10
          
      - name: 3Auto Issue List in README
        uses: zhang0ZGC/issue-list-readme@master
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- 3issueTable -->"
          state: "closed"
          labels: "果子学生信,fetched"
          creator: "ixxmu"
          per_page: 10
      - name: add-and-commit
        uses: EndBug/add-and-commit@v4
        with:
          message: README.md has been re-written
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
