name: Ruby

on:
  issues:
    types: [opened]
    #schedule:
     #- cron: '0 */24 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - uses: ruby/setup-ruby@v1.190.0
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run:
        bundle exec rake
      env:
        TOKEN: ${{ secrets.DUTY_TOKEN }}
        REPO: ${{ github.repository }}     

