name: Ruby

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
        bundler-cache: false
    - run:
        bundle exec rake

    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
        
      env:
        TOKEN: ${{ secrets.DUTY_TOKEN }}
        REPO: ${{ github.repository }}     

