name: push md files to source branch
on:
  workflow_run:
    workflows: ["generate a Markdown file"]
    types:
      - completed
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
        
    - name: Pushes test file to bk
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PUSH_MD }}
      with:
        source_file: 'posts'
        destination_repo: 'ixxmu/duty_bk'
        destination_branch: 'main'
        destination_folder: 'mp_duty/'
        user_email: ${{ secrets.MY_EMAIL }}
        user_name: 'ixxmu'
        commit_message: 'A custom message for the commit'
